# -*- coding: utf-8 -*-
"""D2_PythonCode_chayoung_V1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XlH-I09ipQ7Miu2vtozpLnnKXcBBwqv-
"""

import tkinter as tk

# Define PI instead of using math.pi.
PI = 3.14159265358979323846

# Define MAX_FLOAT instead of using math.isfinite().
# to reject infinity
MAX_FLOAT = 1.7976931348623157e308

# Define TOLERANCE as a small value used to represent near zero,
# because floating-point results may not be exactly zero.
TOLERANCE = 1e-12

# Set a safe maximum number of iterations to prevent an infinite loop,
# when calculate sin,cos
MAX_TERMS = 50


def absolute_value(number):
    if number < 0:
        return -number

    return number

# Convert degrees to radians when Degrees is selected.
# 180 degrees = π radians
def convert_to_radians(angle, unit):
    if unit == "Degrees":
        return (angle / 180.0) * PI

    if unit == "Radians":
        return angle

def reduce_angle(angle_in_radians):
    half_pi = PI / 2.0
    reduced_angle = (
        (angle_in_radians + half_pi) % PI
    ) - half_pi

    return reduced_angle


def calculate_sine_and_cosine(x):
    # First terms of the sine and cosine series.
    sine_term = x
    sine_sum = x

    cosine_term = 1.0
    cosine_sum = 1.0

    term_number = 1

    # Repeatedly generate the next sine and cosine terms from the previous terms.
    while term_number <= MAX_TERMS:
        sine_term = (
            -sine_term * x * x
            / (
                (2 * term_number)
                * (2 * term_number + 1)
            )
        )

        cosine_term = (
            -cosine_term * x * x
            / (
                (2 * term_number - 1)
                * (2 * term_number)
            )
        )

        sine_sum = sine_sum + sine_term
        cosine_sum = cosine_sum + cosine_term

        # Stop when both new terms are too small to affect the result.
        if (
            absolute_value(sine_term) < TOLERANCE
            and absolute_value(cosine_term) < TOLERANCE
        ):
            break

        term_number = term_number + 1

    return sine_sum, cosine_sum

##result check
result = calculate_sine_and_cosine(0.4)
print(f"Result: {result}\n\n\n" )





def calculate_tangent(angle_input, unit):
    # FR-01, FR-05: Check whether the angle was entered correctly.
    if angle_input.strip() == "":
        return "Error: Please enter an angle."

    try:
        angle = float(angle_input)
    except ValueError:
        return "Error: Please enter a numeric angle."

    # Do not accept infinity or NaN.
    if not math.isfinite(angle):
        return "Error: Please enter a finite numeric angle."

    # FR-02: Convert degrees to radians if necessary.
    unit = unit.strip().lower()

    if unit in ["degrees"]:
        x = angle * math.pi / 180

    elif unit in ["radians"]:
        x = angle

    else:
        return "Error: Please select Degrees or Radians."

    # Reduce the angle because tangent repeats every pi radians.
    x = x - round(x / math.pi) * math.pi

    # FR-06: Tangent is undefined at pi/2 + k*pi.
    if abs(abs(x) - math.pi / 2) < TOLERANCE:
        return "Undefined"

    # Start with the first terms of the sine and cosine series.
    sine_term = x
    sine_sum = x

    cosine_term = 1
    cosine_sum = 1

    # FR-03, NFR-01: Calculate sine and cosine using Taylor series.
    for n in range(1, MAX_TERMS + 1):
        sine_term = (
            -sine_term * x * x
            / ((2 * n) * (2 * n + 1))
        )

        cosine_term = (
            -cosine_term * x * x
            / ((2 * n - 1) * (2 * n))
        )

        sine_sum += sine_term
        cosine_sum += cosine_term

        # Stop when both new terms become very small.
        if (
            abs(sine_term) < TOLERANCE
            and abs(cosine_term) < TOLERANCE
        ):
            break

    # Prevent division by a value very close to zero.
    if abs(cosine_sum) < TOLERANCE:
        return "Undefined"

    return sine_sum / cosine_sum


# NFR-02: Text-based interface with clear labels.
print("Tangent Calculator")
print("------------------")
print("Type 'exit' in the angle field to stop.")

while True:
    print()

    angle_input = input("Angle: ")

    if angle_input.strip().lower() == "exit":
        print("Calculator stopped.")
        break

    unit = input("Unit (Degrees or Radians): ")

    result = calculate_tangent(angle_input, unit)

    # FR-04: Display the result clearly.
    if isinstance(result, float):
        print(f"Result: {result:.6f}")
    else:
        print(f"Result: {result}")